// src/components/vault/coachStaticManifest.js
// ─────────────────────────────────────────────────────────────────────────────
// MARGIN GUARD — Static Coach-Cue resolver (client side).
//
// Maps a live movement name (program exercise OR prehab drill) to its pre-baked
// static clip slug, so the UI can play /media/coach-static/<slug>.<locale>.mp3
// via <CoachVoiceNote slug={…} /> INSTEAD of pinging bbf-biokinetic-briefing.
// The actual TTS scripts never reach the client — only the resolution map does.
//
// The JSON is GENERATED by scripts/build-coach-static-manifest.mjs (the single
// source of truth). When a movement has no static clip (e.g. a one-off AI-injected
// movement in a custom plan), the resolver returns null and the caller keeps the
// dynamic path as a fallback — so margins are protected for the known library
// without breaking bespoke plans.

import MANIFEST from '../../data/coachStaticManifest.json';

// ── Clip delivery ────────────────────────────────────────────────────────────
// PRIMARY: repo-static — frontend/public/media/coach-static, served same-origin
// and SW-cached — once scripts/sync-coach-static.mjs has mirrored the one-time
// bake into the repo. FALLBACK: the public Supabase bucket the baker uploads to,
// so the clips are LIVE in production immediately (still 100% static — no synth,
// no backend ping) even before the repo mirror lands. <CoachVoiceNote> tries the
// repo path first and swaps to the bucket on a 404.
export const COACH_STATIC_REPO_BASE = '/media/coach-static';
export const COACH_STATIC_BUCKET_BASE = 'https://ihclbceghxpuawymlvgi.supabase.co/storage/v1/object/public/coach-static';

// Must match the normalization used by the build script.
const norm = (s) => String(s || '').toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim();

// Generic, localized one-liners for the clip subtitle (the title is the live
// movement name the host component already renders, so no per-exercise copy here).
const TOPIC = {
  program: {
    en: 'Form cue — own the movement.',
    es: 'Indicación de técnica — domina el movimiento.',
    pt: 'Comando de execução — domine o movimento.',
  },
  prehab: {
    en: 'Prehab cue — dial in the drill.',
    es: 'Indicación de prehab — ajusta el ejercicio.',
    pt: 'Comando de prehab — ajuste o exercício.',
  },
};

const EYEBROW = { en: "Coach's Voice", es: 'La Voz del Coach', pt: 'A Voz do Coach' };

// Resolve a program exercise name → static slug (or null when not in the library).
export function programSlug(name) {
  return MANIFEST.program[norm(name)] || null;
}

// Resolve a prehab drill's English name → static slug (or null). DiagnosisResult
// keys cues by the drill's English name, mirroring the build script.
export function prehabSlug(enName) {
  return MANIFEST.prehab[norm(enName)] || null;
}

export function hasStaticClip(slug) {
  return Boolean(slug) && MANIFEST.slugs.includes(slug);
}

// Localized subtitle + eyebrow for a slug clip, by kind.
export function staticTopic(slug, lang) {
  const k = MANIFEST.kind[slug] || 'program';
  const dict = TOPIC[k] || TOPIC.program;
  return dict[lang] || dict.en;
}

export function staticEyebrow(lang) {
  return EYEBROW[lang] || EYEBROW.en;
}

export default MANIFEST;
