// src/components/vault/exerciseGifs.js
// ─────────────────────────────────────────────────────────────────────────────
// Quick-View GIF resolver — the lightweight animated-loop side of the
// Dual-Media exercise card (the 🎬 video summary side stays exerciseVideos.js).
//
// Source of truth: frontend/src/data/exerciseGifManifest.json, GENERATED by
// scripts/map-exercise-gifs.mjs from the repo-root ./videos folder. The
// manifest maps authorized exercise names → gif filenames; this module only
// resolves plan names against it (same normalizer as the video map, so the two
// media indexes can never drift).
//
// IMMUTABLE LAW (inherited from the VIDEO_MAP): the manifest is built strictly
// from the authorized catalog, so a blacklisted lift is simply absent and can
// never resolve to a loop — the map is the allow-list, not just media.
//
// No match → null → the card renders the branded BBF placeholder (never a
// broken image, never a missing panel). Hosting is env-switchable: set
// VITE_EXERCISE_GIF_BASE (e.g. a Supabase Storage public bucket URL) to move
// the loops off-origin without touching a component.

import manifest from '../../data/exerciseGifManifest.json';
import { normalizeExerciseName } from './exerciseVideos.js';

const GIF_BASE =
  (typeof import.meta !== 'undefined' && import.meta.env && import.meta.env.VITE_EXERCISE_GIF_BASE) ||
  '/videos/';

const MATCHED = (manifest && manifest.matched) || {};

// Precomputed normalized index over the manifest keys (built once, tiny).
const GIF_INDEX = Object.keys(MATCHED).map((name) => ({
  file: MATCHED[name],
  norm: normalizeExerciseName(name).join(' '),
}));

// Resolve a plan exercise name to its quick-view loop URL, or null.
// Exact manifest key → exact normalized key. No fuzzy pass at runtime: the
// build-time mapper already did the fuzzy work under human-auditable rules.
export function resolveGifUrl(exName) {
  if (MATCHED[exName]) return GIF_BASE + MATCHED[exName];
  const norm = normalizeExerciseName(exName).join(' ');
  if (!norm) return null;
  for (let i = 0; i < GIF_INDEX.length; i++) {
    if (GIF_INDEX[i].norm === norm) return GIF_BASE + GIF_INDEX[i].file;
  }
  return null;
}

// True when the ingestion pipeline has ANY matched loops — lets a surface skip
// rendering the Quick-View affordance entirely while the manifest is empty
// (today's state: 1,324 opaque `NNNN-hash.gif` exports await manifest overrides).
export function hasGifLibrary() {
  return GIF_INDEX.length > 0;
}
