// ═══════════════════════════════════════════════════════════════
// WORKOUT-DATA.JS — BBF Global Scouting Hub
// Laboratory Generated — Pending Founder Audit
// NASM-CPT Biomechanical Principles · KPI-Targeted Drills
// Built on the 175 LB Blueprint. Data-driven, Athlete-tested.
// ═══════════════════════════════════════════════════════════════
var WORKOUT_CATALOG = {
football: {
  QB: [
    {name:{en:'Rotational Med-Ball Slam',es:'Golpe Rotacional con Balón Medicinal',pt:'Slam Rotacional com Medicine Ball'},sets:'4x8/side',focus:{en:'Rotational torque — hip-to-shoulder separation for throwing velocity',es:'Torque rotacional — separación cadera-hombro para velocidad de lanzamiento',pt:'Torque rotacional — separação quadril-ombro para velocidade de lançamento'},equipment:'Med Ball',kpi:'Rotational Torque'},
    {name:{en:'Band-Resisted Drop Step',es:'Paso de Retroceso con Banda',pt:'Passo de Recuo com Faixa'},sets:'4x6/side',focus:{en:'Pocket maneuverability — lateral escape speed under pressure',es:'Maniobrabilidad de bolsillo — velocidad de escape lateral bajo presión',pt:'Manobrabilidade de pocket — velocidade de escape lateral sob pressão'},equipment:'Band',kpi:'Pocket Maneuverability'},
    {name:{en:'Single-Leg RDL to Overhead Press',es:'Peso Muerto Rumano Unilateral a Press',pt:'Levantamento Terra Romeno Unilateral para Press'},sets:'3x8/side',focus:{en:'Throwing velocity — integrated kinetic chain from ground to release',es:'Velocidad de lanzamiento — cadena cinética integrada del suelo al lanzamiento',pt:'Velocidade de lançamento — cadeia cinética integrada do solo ao lançamento'},equipment:'DB',kpi:'Throwing Velocity'}
  ],
  RB: [
    {name:{en:'Lateral Bound to Sprint',es:'Salto Lateral a Sprint',pt:'Salto Lateral para Sprint'},sets:'4x4/side',focus:{en:'Lateral agility — cut speed and first-step redirection',es:'Agilidad lateral — velocidad de corte y redirección del primer paso',pt:'Agilidade lateral — velocidade de corte e redirecionamento do primeiro passo'},equipment:'BW',kpi:'Lateral Agility'},
    {name:{en:'Trap Bar Deadlift',es:'Peso Muerto con Barra Hexagonal',pt:'Levantamento Terra com Barra Hexagonal'},sets:'5x5 @80%',focus:{en:'Triple extension power — hip-knee-ankle drive for acceleration',es:'Potencia de triple extensión — impulso cadera-rodilla-tobillo para aceleración',pt:'Potência de tripla extensão — impulso quadril-joelho-tornozelo para aceleração'},equipment:'Trap Bar',kpi:'Triple Extension Power'},
    {name:{en:'Farmer Carry with Direction Change',es:'Cargada de Granjero con Cambio de Dirección',pt:'Caminhada do Fazendeiro com Mudança de Direção'},sets:'4x30yd',focus:{en:'Ball security stability — trunk rigidity under load and movement',es:'Estabilidad de seguridad del balón — rigidez del tronco bajo carga y movimiento',pt:'Estabilidade de segurança da bola — rigidez do tronco sob carga e movimento'},equipment:'DB/KB',kpi:'Ball Security Stability'}
  ],
  WR: [
    {name:{en:'Box Jump to 10yd Sprint',es:'Salto al Cajón a Sprint de 10yd',pt:'Salto na Caixa para Sprint de 10yd'},sets:'4x5',focus:{en:'Linear acceleration — reactive power off the line of scrimmage',es:'Aceleración lineal — potencia reactiva desde la línea de scrimmage',pt:'Aceleração linear — potência reativa da linha de scrimmage'},equipment:'Box',kpi:'Linear Acceleration'},
    {name:{en:'5-10-5 Pro Agility Shuttle',es:'Shuttle de Agilidad Pro 5-10-5',pt:'Shuttle de Agilidade Pro 5-10-5'},sets:'4x reps',focus:{en:'Change of direction — hip transition speed in route breaks',es:'Cambio de dirección — velocidad de transición de cadera en cortes de ruta',pt:'Mudança de direção — velocidade de transição de quadril em quebras de rota'},equipment:'Cones',kpi:'Change of Direction'},
    {name:{en:'Plate Pinch Hold',es:'Agarre de Plato con Pinza',pt:'Pegada de Anilha em Pinça'},sets:'3x30s',focus:{en:'Grip strength — hand endurance for contested catches',es:'Fuerza de agarre — resistencia de manos para recepciones disputadas',pt:'Força de pegada — resistência de mãos para recepções disputadas'},equipment:'Plate',kpi:'Grip Strength'}
  ],
  TE: [
    {name:{en:'Hang Clean',es:'Cargada Colgante',pt:'Clean Suspenso'},sets:'5x3',focus:{en:'Triple extension power — explosive hip drive for blocking and receiving',es:'Potencia de triple extensión — impulso explosivo de cadera para bloqueo y recepción',pt:'Potência de tripla extensão — impulso explosivo de quadril para bloqueio e recepção'},equipment:'Barbell',kpi:'Triple Extension Power'},
    {name:{en:'Sled Drive to Sustain',es:'Empuje de Trineo Sostenido',pt:'Empurrão de Trenó Sustentado'},sets:'4x15yd',focus:{en:'Blocking leverage — sustained force at point of attack',es:'Palanca de bloqueo — fuerza sostenida en punto de ataque',pt:'Alavancagem de bloqueio — força sustentada no ponto de ataque'},equipment:'Sled',kpi:'Blocking Leverage'},
    {name:{en:'400m Repeats with Resistance',es:'Repeticiones de 400m con Resistencia',pt:'Repetições de 400m com Resistência'},sets:'4x400m',focus:{en:'Versatility endurance — sustained output across varied game demands',es:'Resistencia versátil — rendimiento sostenido a través de demandas variadas',pt:'Resistência versátil — rendimento sustentado através de demandas variadas'},equipment:'Track',kpi:'Versatility Endurance'}
  ],
  OL: [
    {name:{en:'Pause Squat',es:'Sentadilla con Pausa',pt:'Agachamento com Pausa'},sets:'5x3 @85%',focus:{en:'Static strength — isometric force production in pass-protection stance',es:'Fuerza estática — producción de fuerza isométrica en posición de protección',pt:'Força estática — produção de força isométrica na posição de proteção'},equipment:'Barbell',kpi:'Static Strength/Force'},
    {name:{en:'Lateral Sled Drag',es:'Arrastre Lateral de Trineo',pt:'Arrasto Lateral de Trenó'},sets:'4x20yd/side',focus:{en:'Lateral displacement — mirror and redirect ability against speed rushers',es:'Desplazamiento lateral — capacidad de espejo y redirección contra rushers rápidos',pt:'Deslocamento lateral — capacidade de espelho e redirecionamento contra rushers rápidos'},equipment:'Sled',kpi:'Lateral Displacement'},
    {name:{en:'Pallof Press ISO Hold',es:'Press Pallof con Pausa Isométrica',pt:'Press Pallof com Pausa Isométrica'},sets:'3x20s/side',focus:{en:'Core stability — anti-rotation under contact and torque',es:'Estabilidad del core — anti-rotación bajo contacto y torque',pt:'Estabilidade do core — anti-rotação sob contato e torque'},equipment:'Cable/Band',kpi:'Core Stability'}
  ],
  DL: [
    {name:{en:'Power Clean from Blocks',es:'Cargada de Potencia desde Bloques',pt:'Power Clean dos Blocos'},sets:'5x3',focus:{en:'Peak explosive power — maximal rate of force development',es:'Potencia explosiva máxima — tasa máxima de desarrollo de fuerza',pt:'Potência explosiva máxima — taxa máxima de desenvolvimento de força'},equipment:'Barbell',kpi:'Peak Explosive Power'},
    {name:{en:'Rotational Med-Ball Scoop Toss',es:'Lanzamiento Rotacional con Balón Medicinal',pt:'Arremesso Rotacional com Medicine Ball'},sets:'4x6/side',focus:{en:'Shedding torque — rotational force to disengage from blockers',es:'Torque de liberación — fuerza rotacional para liberarse de bloqueadores',pt:'Torque de liberação — força rotacional para se livrar de bloqueadores'},equipment:'Med Ball',kpi:'Shedding Torque'},
    {name:{en:'Sprinter Start to 5yd Burst',es:'Salida de Sprinter a Explosión de 5yd',pt:'Saída de Sprinter para Explosão de 5yd'},sets:'6x reps',focus:{en:'First-step velocity — initial burst off the snap',es:'Velocidad del primer paso — explosión inicial desde el snap',pt:'Velocidade do primeiro passo — explosão inicial do snap'},equipment:'Blocks',kpi:'First-Step Velocity'}
  ],
  LB: [
    {name:{en:'Lateral Shuffle to Tackle Pad',es:'Desplazamiento Lateral a Escudo de Tacleo',pt:'Deslocamento Lateral para Escudo de Tackle'},sets:'4x6/side',focus:{en:'Lateral tracking — pursuit angle and hip fluidity',es:'Seguimiento lateral — ángulo de persecución y fluidez de cadera',pt:'Rastreamento lateral — ângulo de perseguição e fluidez de quadril'},equipment:'Cones/Pad',kpi:'Lateral Tracking'},
    {name:{en:'Incline Barbell Press',es:'Press Inclinado con Barra',pt:'Supino Inclinado com Barra'},sets:'4x6',focus:{en:'Tackling force — upper-body pressing power for shedding blocks',es:'Fuerza de tacleo — potencia de empuje superior para liberarse de bloqueos',pt:'Força de tackle — potência de empurrão superior para se livrar de bloqueios'},equipment:'Barbell',kpi:'Tackling Force'},
    {name:{en:'Reactive Agility Cone Drill',es:'Ejercicio Reactivo de Agilidad con Conos',pt:'Exercício Reativo de Agilidade com Cones'},sets:'4x8',focus:{en:'Reactive agility — read-and-react speed to visual stimulus',es:'Agilidad reactiva — velocidad de lectura y reacción a estímulo visual',pt:'Agilidade reativa — velocidade de leitura e reação a estímulo visual'},equipment:'Cones',kpi:'Reactive Agility'}
  ],
  S: [
    {name:{en:'Flying 40yd Sprint',es:'Sprint Lanzado de 40 Yardas',pt:'Sprint Lançado de 40 Jardas'},sets:'4x reps',focus:{en:'Top-end speed — max velocity for deep coverage',es:'Velocidad máxima — velocidad tope para cobertura profunda',pt:'Velocidade máxima — velocidade de pico para cobertura profunda'},equipment:'Track',kpi:'Top-End Speed'},
    {name:{en:'Backpedal to Break Drill',es:'Retroceso a Quiebre',pt:'Recuo para Quebra'},sets:'4x8',focus:{en:'Transition velocity — hip flip speed from backpedal to drive',es:'Velocidad de transición — velocidad de giro de cadera de retroceso a impulso',pt:'Velocidade de transição — velocidade de giro de quadril de recuo para impulso'},equipment:'Cones',kpi:'Transition Velocity'},
    {name:{en:'Depth Jump to Vertical',es:'Salto de Profundidad a Vertical',pt:'Salto de Profundidade para Vertical'},sets:'4x4',focus:{en:'Vertical displacement — reactive jump height for interceptions',es:'Desplazamiento vertical — altura de salto reactivo para intercepciones',pt:'Deslocamento vertical — altura de salto reativo para interceptações'},equipment:'Box',kpi:'Vertical Displacement'}
  ]
},
basketball: {
  PG: [
    {name:{en:'Suicide Sprint Series',es:'Serie de Sprints Suicidas',pt:'Série de Sprints Suicidas'},sets:'4x sets',focus:{en:'Repeat sprint ability — sustain max effort across possessions',es:'Capacidad de sprint repetido — mantener esfuerzo máximo entre posesiones',pt:'Capacidade de sprint repetido — manter esforço máximo entre posses'},equipment:'Court',kpi:'Repeat Sprint Ability'},
    {name:{en:'Tennis Ball Dribble Drill',es:'Dribling con Pelota de Tenis',pt:'Drible com Bola de Tênis'},sets:'3x60s',focus:{en:'Ball handling precision — dual-task coordination under speed',es:'Precisión de manejo de balón — coordinación dual bajo velocidad',pt:'Precisão de manejo de bola — coordenação dual sob velocidade'},equipment:'Tennis Ball + Basketball',kpi:'Ball Handling Precision'},
    {name:{en:'Peripheral Vision Passing Drill',es:'Ejercicio de Pase con Visión Periférica',pt:'Exercício de Passe com Visão Periférica'},sets:'3x sets',focus:{en:'Peripheral vision — court awareness while processing multiple threats',es:'Visión periférica — conciencia de cancha procesando múltiples amenazas',pt:'Visão periférica — consciência de quadra processando múltiplas ameaças'},equipment:'Cones + Ball',kpi:'Peripheral Vision'}
  ],
  SG: [
    {name:{en:'Pull-Up Jump Shot Series',es:'Serie de Tiros en Suspensión',pt:'Série de Arremessos em Suspensão'},sets:'5x10',focus:{en:'Shooting velocity — quick-release mechanics under defensive pressure',es:'Velocidad de tiro — mecánica de liberación rápida bajo presión defensiva',pt:'Velocidade de arremesso — mecânica de liberação rápida sob pressão defensiva'},equipment:'Court + Ball',kpi:'Shooting Velocity'},
    {name:{en:'Full-Court Sprint Layup',es:'Sprint de Cancha Completa a Bandeja',pt:'Sprint de Quadra Inteira para Bandeja'},sets:'4x6',focus:{en:'Transition speed — end-to-end burst in fast break scenarios',es:'Velocidad de transición — explosión de extremo a extremo en contraataque',pt:'Velocidade de transição — explosão ponta a ponta em contra-ataque'},equipment:'Court',kpi:'Transition Speed'},
    {name:{en:'Defensive Slide Series',es:'Serie de Deslizamientos Defensivos',pt:'Série de Deslizamentos Defensivos'},sets:'4x20s',focus:{en:'Lateral flow — sustained low stance and hip fluidity on defense',es:'Fluidez lateral — postura baja sostenida y fluidez de cadera en defensa',pt:'Fluidez lateral — postura baixa sustentada e fluidez de quadril na defesa'},equipment:'Court',kpi:'Lateral Flow'}
  ],
  SF: [
    {name:{en:'Approach Jump to Rim Touch',es:'Salto de Aproximación a Tocar Aro',pt:'Salto de Aproximação para Tocar Aro'},sets:'4x6',focus:{en:'Vertical displacement — max jump height for finishing at the rim',es:'Desplazamiento vertical — altura máxima de salto para finalizar en el aro',pt:'Deslocamento vertical — altura máxima de salto para finalizar no aro'},equipment:'Court',kpi:'Vertical Displacement'},
    {name:{en:'Mirror Agility Drill',es:'Ejercicio de Agilidad en Espejo',pt:'Exercício de Agilidade em Espelho'},sets:'4x30s',focus:{en:'Multi-directional quickness — reactive movement mirroring an opponent',es:'Rapidez multidireccional — movimiento reactivo reflejando a un oponente',pt:'Rapidez multidirecional — movimento reativo espelhando um oponente'},equipment:'Partner',kpi:'Multi-Directional Quickness'},
    {name:{en:'Triple-Threat Jab Step Series',es:'Serie de Paso de Ataque Triple Amenaza',pt:'Série de Passo de Ataque Tripla Ameaça'},sets:'4x8/side',focus:{en:'Triple-threat torque — rotational power from catch to attack position',es:'Torque de triple amenaza — potencia rotacional de recepción a posición de ataque',pt:'Torque de tripla ameaça — potência rotacional da recepção à posição de ataque'},equipment:'Ball',kpi:'Triple-Threat Torque'}
  ],
  PF: [
    {name:{en:'Hang Clean',es:'Cargada Colgante',pt:'Clean Suspenso'},sets:'5x3',focus:{en:'Triple extension power — explosive hip drive for rebounding',es:'Potencia de triple extensión — impulso explosivo de cadera para rebote',pt:'Potência de tripla extensão — impulso explosivo de quadril para rebote'},equipment:'Barbell',kpi:'Triple Extension Power'},
    {name:{en:'Box Out to Vertical Jump',es:'Bloqueo de Rebote a Salto Vertical',pt:'Bloqueio de Rebote para Salto Vertical'},sets:'4x6',focus:{en:'Rebounding force — contact absorption into vertical displacement',es:'Fuerza de rebote — absorción de contacto hacia desplazamiento vertical',pt:'Força de rebote — absorção de contato para deslocamento vertical'},equipment:'Box/Pad',kpi:'Rebounding Force'},
    {name:{en:'Single-Leg Balance Row',es:'Remo en Equilibrio Unilateral',pt:'Remada em Equilíbrio Unilateral'},sets:'3x10/side',focus:{en:'Post-stability — trunk control under single-leg loading',es:'Estabilidad de poste — control del tronco bajo carga unilateral',pt:'Estabilidade de poste — controle do tronco sob carga unilateral'},equipment:'DB',kpi:'Post-Stability'}
  ],
  C: [
    {name:{en:'Block Press to Vertical',es:'Press de Bloqueo a Vertical',pt:'Press de Bloqueio para Vertical'},sets:'4x6',focus:{en:'Rim protection power — hand speed and vertical reach at the basket',es:'Potencia de protección de aro — velocidad de manos y alcance vertical',pt:'Potência de proteção de aro — velocidade de mãos e alcance vertical'},equipment:'Pad',kpi:'Rim Protection Power'},
    {name:{en:'Heavy Goblet Squat Hold',es:'Sentadilla Goblet Pesada con Pausa',pt:'Agachamento Goblet Pesado com Pausa'},sets:'4x20s',focus:{en:'Static strength — isometric lower body force for post defense',es:'Fuerza estática — fuerza isométrica inferior para defensa de poste',pt:'Força estática — força isométrica inferior para defesa de poste'},equipment:'KB',kpi:'Static Strength'},
    {name:{en:'Drop-Step Pivot Series',es:'Serie de Pivote con Paso de Caída',pt:'Série de Pivô com Passo de Queda'},sets:'4x8/side',focus:{en:'Pivot speed — foot speed and hip rotation in the paint',es:'Velocidad de pivote — velocidad de pies y rotación de cadera en la pintura',pt:'Velocidade de pivô — velocidade de pés e rotação de quadril no garrafão'},equipment:'Court',kpi:'Pivot Speed'}
  ]
},
soccer: {
  FW: [
    {name:{en:'Flying 30m Sprint',es:'Sprint Lanzado de 30m',pt:'Sprint Lançado de 30m'},sets:'6x reps',focus:{en:'Sprint velocity — max speed for breaking defensive lines',es:'Velocidad de sprint — velocidad máxima para romper líneas defensivas',pt:'Velocidade de sprint — velocidade máxima para romper linhas defensivas'},equipment:'Cones',kpi:'Sprint Velocity'},
    {name:{en:'Finishing Drill Under Fatigue',es:'Ejercicio de Definición bajo Fatiga',pt:'Exercício de Finalização sob Fadiga'},sets:'4x sets',focus:{en:'Shot conversion — accuracy and composure after high-intensity runs',es:'Conversión de disparo — precisión y compostura después de carreras intensas',pt:'Conversão de chute — precisão e compostura após corridas intensas'},equipment:'Balls/Goal',kpi:'Shot Conversion Rate'},
    {name:{en:'Plyometric Lunge to Sprint',es:'Zancada Pliométrica a Sprint',pt:'Avanço Pliométrico para Sprint'},sets:'4x5/side',focus:{en:'Off-ball acceleration — explosive first step from standing or jogging',es:'Aceleración sin balón — primer paso explosivo desde posición estática',pt:'Aceleração sem bola — primeiro passo explosivo da posição estática'},equipment:'BW',kpi:'Off-Ball Acceleration'}
  ],
  MF: [
    {name:{en:'Yo-Yo Intermittent Recovery Test',es:'Test de Recuperación Intermitente Yo-Yo',pt:'Teste de Recuperação Intermitente Yo-Yo'},sets:'Protocol',focus:{en:'Total distance — aerobic capacity for 90-minute match demands',es:'Distancia total — capacidad aeróbica para demandas de partidos de 90 minutos',pt:'Distância total — capacidade aeróbica para demandas de jogos de 90 minutos'},equipment:'Cones',kpi:'Total Distance'},
    {name:{en:'Pressured Passing Circuit',es:'Circuito de Pases bajo Presión',pt:'Circuito de Passes sob Pressão'},sets:'3x sets',focus:{en:'Pass completion under pressure — decision-making speed with the ball',es:'Completación de pases bajo presión — velocidad de decisión con balón',pt:'Conclusão de passes sob pressão — velocidade de decisão com bola'},equipment:'Balls/Partners',kpi:'Pass Completion'},
    {name:{en:'Shadow Interception Drill',es:'Ejercicio de Intercepción en Sombra',pt:'Exercício de Interceptação em Sombra'},sets:'4x sets',focus:{en:'Interception anticipation — reading passing lanes and body positioning',es:'Anticipación de intercepción — lectura de líneas de pase y posicionamiento',pt:'Antecipação de interceptação — leitura de linhas de passe e posicionamento'},equipment:'Cones/Partners',kpi:'Interception Anticipation'}
  ],
  DEF: [
    {name:{en:'Header Duel Box Drill',es:'Ejercicio de Duelo Aéreo en Caja',pt:'Exercício de Duelo Aéreo na Área'},sets:'4x sets',focus:{en:'Aerial duel win rate — timing, positioning, and neck strength',es:'Tasa de ganancia de duelos aéreos — timing, posicionamiento y fuerza cervical',pt:'Taxa de vitória em duelos aéreos — timing, posicionamento e força cervical'},equipment:'Balls',kpi:'Aerial Duel Win%'},
    {name:{en:'Recovery Sprint Intervals',es:'Intervalos de Sprint de Recuperación',pt:'Intervalos de Sprint de Recuperação'},sets:'8x60m',focus:{en:'Recovery sprint speed — closing down attackers after being beaten',es:'Velocidad de sprint de recuperación — cerrar sobre atacantes después de ser superado',pt:'Velocidade de sprint de recuperação — fechar sobre atacantes após ser superado'},equipment:'Cones',kpi:'Recovery Sprint Speed'},
    {name:{en:'1v1 Tackling Circuit',es:'Circuito de Tacleo 1v1',pt:'Circuito de Tackle 1v1'},sets:'4x sets',focus:{en:'Tackling efficiency — clean ball-winning technique without fouling',es:'Eficiencia de tacleo — técnica limpia de recuperación sin falta',pt:'Eficiência de tackle — técnica limpa de recuperação sem falta'},equipment:'Balls/Cones',kpi:'Tackling Efficiency'}
  ],
  GK: [
    {name:{en:'Reaction Ball Save Drill',es:'Ejercicio de Atajada con Pelota de Reacción',pt:'Exercício de Defesa com Bola de Reação'},sets:'3x60s',focus:{en:'Reaction time — neural processing speed for close-range saves',es:'Tiempo de reacción — velocidad de procesamiento neural para atajadas cercanas',pt:'Tempo de reação — velocidade de processamento neural para defesas próximas'},equipment:'Reaction Ball',kpi:'Reaction Time'},
    {name:{en:'Lateral Dive Series',es:'Serie de Lanzamientos Laterales',pt:'Série de Mergulhos Laterais'},sets:'4x6/side',focus:{en:'Lateral displacement power — explosive dive reach across the goal',es:'Potencia de desplazamiento lateral — alcance explosivo de lanzamiento en la portería',pt:'Potência de deslocamento lateral — alcance explosivo de mergulho no gol'},equipment:'Goal/Balls',kpi:'Lateral Displacement Power'},
    {name:{en:'Long Distribution Accuracy Drill',es:'Ejercicio de Distribución Larga',pt:'Exercício de Distribuição Longa'},sets:'3x10',focus:{en:'Distribution accuracy — goal kick and throw precision under pressure',es:'Precisión de distribución — precisión de saque de meta y lanzamiento bajo presión',pt:'Precisão de distribuição — precisão de tiro de meta e lançamento sob pressão'},equipment:'Balls/Cones',kpi:'Distribution Accuracy'}
  ]
},
baseball: {
  P: [
    {name:{en:'Reverse Lunge to Rotation',es:'Zancada Inversa con Rotación',pt:'Avanço Reverso com Rotação'},sets:'3x8/side',focus:{en:'Kinetic sequencing — hip-to-shoulder separation for pitch velocity',es:'Secuenciación cinética — separación cadera-hombro para velocidad de lanzamiento',pt:'Sequenciamento cinético — separação quadril-ombro para velocidade de lançamento'},equipment:'Med Ball',kpi:'Kinetic Sequencing'},
    {name:{en:'Band Shoulder ER/IR Protocol',es:'Protocolo de Rotación Externa/Interna con Banda',pt:'Protocolo de Rotação Externa/Interna com Faixa'},sets:'3x15/direction',focus:{en:'Scapular deceleration — rotator cuff durability for arm longevity',es:'Desaceleración escapular — durabilidad del manguito rotador para longevidad del brazo',pt:'Desaceleração escapular — durabilidade do manguito rotador para longevidade do braço'},equipment:'Band',kpi:'Scapular Deceleration'},
    {name:{en:'Weighted Ball Velocity Throws',es:'Lanzamientos de Velocidad con Pelota Pesada',pt:'Arremessos de Velocidade com Bola Pesada'},sets:'4x8',focus:{en:'Pitch velocity — overload/underload training for arm speed',es:'Velocidad de lanzamiento — entrenamiento de sobrecarga/subcarga para velocidad del brazo',pt:'Velocidade de lançamento — treino de sobrecarga/subcarga para velocidade do braço'},equipment:'Weighted Balls',kpi:'Pitch Velocity'}
  ],
  C: [
    {name:{en:'Squat to Explosive Stand',es:'Sentadilla a Levantamiento Explosivo',pt:'Agachamento para Levantamento Explosivo'},sets:'4x6',focus:{en:'Pop-to-pop time — squat-to-throw transition speed',es:'Tiempo pop-a-pop — velocidad de transición sentadilla-a-lanzamiento',pt:'Tempo pop-a-pop — velocidade de transição agachamento-para-arremesso'},equipment:'Barbell',kpi:'Pop-to-Pop Time'},
    {name:{en:'Lateral Block Drill',es:'Ejercicio de Bloqueo Lateral',pt:'Exercício de Bloqueio Lateral'},sets:'4x8/side',focus:{en:'Lateral blocking speed — quick-twitch redirection from receiving stance',es:'Velocidad de bloqueo lateral — redirección rápida desde posición de recepción',pt:'Velocidade de bloqueio lateral — redirecionamento rápido da posição de recepção'},equipment:'Balls/Pad',kpi:'Lateral Blocking Speed'},
    {name:{en:'Single-Leg Squat Hold',es:'Sentadilla Unilateral con Pausa',pt:'Agachamento Unilateral com Pausa'},sets:'3x15s/side',focus:{en:'Receiving stability — isometric knee and ankle control in crouch',es:'Estabilidad de recepción — control isométrico de rodilla y tobillo en cuclillas',pt:'Estabilidade de recepção — controle isométrico de joelho e tornozelo agachado'},equipment:'BW',kpi:'Receiving Stability'}
  ],
  IF: [
    {name:{en:'Lateral Bound Stick',es:'Salto Lateral con Estabilización',pt:'Salto Lateral com Estabilização'},sets:'4x5/side',focus:{en:'Lateral agility — fielding range and single-leg deceleration',es:'Agilidad lateral — rango de fildeo y desaceleración unilateral',pt:'Agilidade lateral — alcance de campo e desaceleração unilateral'},equipment:'BW',kpi:'Lateral Agility'},
    {name:{en:'Quick-Hands Transfer Drill',es:'Ejercicio de Transferencia Rápida de Manos',pt:'Exercício de Transferência Rápida de Mãos'},sets:'4x20',focus:{en:'Ball exchange speed — glove-to-hand-to-throw transfer time',es:'Velocidad de intercambio de pelota — tiempo de transferencia guante-mano-lanzamiento',pt:'Velocidade de troca de bola — tempo de transferência luva-mão-arremesso'},equipment:'Balls/Glove',kpi:'Ball Exchange Speed'},
    {name:{en:'Rotational Med-Ball Scoop Throw',es:'Lanzamiento Rotacional con Balón Medicinal',pt:'Arremesso Rotacional com Medicine Ball'},sets:'4x6/side',focus:{en:'Rotational throw force — power generation from lower half',es:'Fuerza de lanzamiento rotacional — generación de potencia desde tren inferior',pt:'Força de arremesso rotacional — geração de potência a partir do trem inferior'},equipment:'Med Ball',kpi:'Rotational Throw Force'}
  ],
  OF: [
    {name:{en:'10-20-30m Build-Up Sprint',es:'Sprint Progresivo 10-20-30m',pt:'Sprint Progressivo 10-20-30m'},sets:'4x reps',focus:{en:'Linear acceleration — closing speed on fly balls',es:'Aceleración lineal — velocidad de cierre en elevados',pt:'Aceleração linear — velocidade de fechamento em bolas aéreas'},equipment:'Cones',kpi:'Linear Acceleration'},
    {name:{en:'Drop-Step Crossover Drill',es:'Ejercicio de Paso Cruzado con Caída',pt:'Exercício de Passo Cruzado com Queda'},sets:'4x6/side',focus:{en:'Drop-step efficiency — first-move technique on balls hit overhead',es:'Eficiencia de paso de caída — técnica del primer movimiento en elevados',pt:'Eficiência de passo de queda — técnica do primeiro movimento em bolas aéreas'},equipment:'Cones/Balls',kpi:'Drop-Step Efficiency'},
    {name:{en:'Long-Toss Progression',es:'Progresión de Lanzamiento Largo',pt:'Progressão de Arremesso Longo'},sets:'Protocol',focus:{en:'Arm strength — distance throwing capacity for relay accuracy',es:'Fuerza del brazo — capacidad de lanzamiento a distancia para precisión de relevo',pt:'Força do braço — capacidade de arremesso a distância para precisão de relé'},equipment:'Balls',kpi:'Arm Strength'}
  ]
},
volleyball: {
  S: [
    {name:{en:'Repeated Jump Protocol',es:'Protocolo de Saltos Repetidos',pt:'Protocolo de Saltos Repetidos'},sets:'4x15',focus:{en:'Jump count tolerance — sustained vertical output across a match',es:'Tolerancia de conteo de saltos — producción vertical sostenida durante un partido',pt:'Tolerância de contagem de saltos — produção vertical sustentada durante um jogo'},equipment:'BW',kpi:'Jump Count Tolerance'},
    {name:{en:'Wall-Set Accuracy Drill',es:'Ejercicio de Precisión de Colocación en Pared',pt:'Exercício de Precisão de Levantamento na Parede'},sets:'3x30',focus:{en:'Setting precision — hand contact consistency under fatigue',es:'Precisión de colocación — consistencia de contacto de manos bajo fatiga',pt:'Precisão de levantamento — consistência de contato de mãos sob fadiga'},equipment:'Wall/Ball',kpi:'Setting Precision'},
    {name:{en:'5-Point Agility Star',es:'Estrella de Agilidad de 5 Puntos',pt:'Estrela de Agilidade de 5 Pontos'},sets:'4x reps',focus:{en:'Movement velocity — court coverage speed between sets',es:'Velocidad de movimiento — velocidad de cobertura de cancha entre colocaciones',pt:'Velocidade de movimento — velocidade de cobertura de quadra entre levantamentos'},equipment:'Cones',kpi:'Movement Velocity'}
  ],
  OH: [
    {name:{en:'Approach Jump with Load',es:'Salto de Aproximación con Carga',pt:'Salto de Aproximação com Carga'},sets:'4x6',focus:{en:'Vertical jump height — max displacement in attack approach',es:'Altura de salto vertical — desplazamiento máximo en aproximación de ataque',pt:'Altura de salto vertical — deslocamento máximo em aproximação de ataque'},equipment:'Vest/BW',kpi:'Vertical Jump Height'},
    {name:{en:'Overhead MB Slam',es:'Golpe con Balón Medicinal sobre la Cabeza',pt:'Slam com Medicine Ball Acima da Cabeça'},sets:'4x8',focus:{en:'Spike velocity — overhead striking power and arm speed',es:'Velocidad de remate — potencia de golpe aéreo y velocidad del brazo',pt:'Velocidade de ataque — potência de golpe aéreo e velocidade do braço'},equipment:'Med Ball',kpi:'Spike Velocity'},
    {name:{en:'10m Sprint Repeats',es:'Repeticiones de Sprint de 10m',pt:'Repetições de Sprint de 10m'},sets:'6x reps',focus:{en:'Explosive acceleration — closing speed for transition plays',es:'Aceleración explosiva — velocidad de cierre para jugadas de transición',pt:'Aceleração explosiva — velocidade de fechamento para jogadas de transição'},equipment:'Cones',kpi:'Explosive Acceleration'}
  ],
  LIB: [
    {name:{en:'Reaction Ball Dig Drill',es:'Ejercicio de Defensa con Pelota de Reacción',pt:'Exercício de Defesa com Bola de Reação'},sets:'3x60s',focus:{en:'Agility and reaction speed — neural processing for unpredictable attacks',es:'Agilidad y velocidad de reacción — procesamiento neural para ataques impredecibles',pt:'Agilidade e velocidade de reação — processamento neural para ataques imprevisíveis'},equipment:'Reaction Ball',kpi:'Agility / Reaction Speed'},
    {name:{en:'Platform Accuracy Series',es:'Serie de Precisión de Plataforma',pt:'Série de Precisão de Plataforma'},sets:'3x20',focus:{en:'Dig accuracy — controlled forearm pass to target zones',es:'Precisión de defensa — pase de antebrazo controlado a zonas objetivo',pt:'Precisão de defesa — passe de antebraço controlado para zonas alvo'},equipment:'Balls/Targets',kpi:'Dig Accuracy'},
    {name:{en:'Low Lateral Shuffle Hold',es:'Desplazamiento Lateral Bajo con Pausa',pt:'Deslocamento Lateral Baixo com Pausa'},sets:'4x20s',focus:{en:'Low-center stability — sustained defensive posture for digs',es:'Estabilidad de centro bajo — postura defensiva sostenida para defensas',pt:'Estabilidade de centro baixo — postura defensiva sustentada para defesas'},equipment:'BW',kpi:'Low-Center Stability'}
  ],
  MB: [
    {name:{en:'Standing Reach to Block Jump',es:'Alcance de Pie a Salto de Bloqueo',pt:'Alcance em Pé para Salto de Bloqueio'},sets:'4x6',focus:{en:'Block reach height — max vertical displacement at the net',es:'Altura de alcance de bloqueo — desplazamiento vertical máximo en la red',pt:'Altura de alcance de bloqueio — deslocamento vertical máximo na rede'},equipment:'Net/BW',kpi:'Block Reach Height'},
    {name:{en:'Lateral Slide to Block',es:'Deslizamiento Lateral a Bloqueo',pt:'Deslizamento Lateral para Bloqueio'},sets:'4x8/side',focus:{en:'Lateral closing speed — slide speed along the net to seal the block',es:'Velocidad de cierre lateral — velocidad de deslizamiento en la red para sellar el bloqueo',pt:'Velocidade de fechamento lateral — velocidade de deslizamento na rede para selar o bloqueio'},equipment:'Net',kpi:'Lateral Closing Speed'},
    {name:{en:'Hang Clean',es:'Cargada Colgante',pt:'Clean Suspenso'},sets:'4x4',focus:{en:'Triple extension power — full-body explosive recruitment for blocking',es:'Potencia de triple extensión — reclutamiento explosivo de cuerpo completo para bloqueo',pt:'Potência de tripla extensão — recrutamento explosivo de corpo inteiro para bloqueio'},equipment:'Barbell',kpi:'Triple Extension Power'}
  ]
}
};
