-- ═══════════════════════════════════════════════════════════════════════════
-- FRONT 3.5 — SOVEREIGN AUDIO AUTO-DAILY (pre-computed premium podcast)
-- ───────────────────────────────────────────────────────────────────────────
-- The morning check-in tripwire (bbf_daily_protocols INSERT/UPDATE) now ALSO fires
-- bbf-sovereign-briefing for GRADUATED, non-locked athletes — composing + synthesizing
-- + caching their daily briefing in the BACKGROUND (fire-and-forget pg_net; never
-- blocks the check-in write). The Vault Hub tile then plays the cached blob instantly.
--
-- UNIT ECONOMICS: the trigger pre-filters to graduated + not-locked (skips mid-
-- calibration / locked accounts). The edge fn does the precise voice_coach check, an
-- IDEMPOTENCY skip (1 generation/athlete/day/locale), and metering — so the expensive
-- Claude + ElevenLabs work fires at most once per athlete per day.
--
-- LOOP-SAFE: the trigger + edge fn write ONLY bbf_sovereign_audio, never
-- bbf_daily_protocols → no recursion.
-- ═══════════════════════════════════════════════════════════════════════════

-- ─── 1 · The cached daily briefing — one row per (athlete, day, locale) ────────
create table if not exists public.bbf_sovereign_audio (
  id             uuid primary key default gen_random_uuid(),
  user_id        uuid not null references public.bbf_users(id) on delete cascade,
  briefing_date  date not null,
  locale         text not null,
  audio_b64      text not null,
  mime           text not null default 'audio/mpeg',
  chars          integer,
  voice_id       text,
  status         text not null default 'ready',
  created_at     timestamptz not null default now(),
  constraint uq_sovereign_audio unique (user_id, briefing_date, locale)
);
create index if not exists idx_sovereign_audio_user_day
  on public.bbf_sovereign_audio (user_id, briefing_date desc);

comment on table public.bbf_sovereign_audio is
  'Phase 3.5 pre-computed daily Sovereign Briefing audio, generated by bbf-sovereign-briefing from the morning check-in tripwire (graduated + voice_coach athletes). One row per athlete/day/locale; service-role only; read by the token-gated bbf_get_sovereign_briefing RPC.';

-- RLS: enabled + FORCED, zero policies (deny-all direct access). Writes = service-role
-- edge fn; reads = the SECURITY DEFINER RPC below.
alter table public.bbf_sovereign_audio enable row level security;
alter table public.bbf_sovereign_audio force  row level security;
revoke all on table public.bbf_sovereign_audio from anon, authenticated;

-- ─── 2 · Arm the shared secret (idempotent — never resets an existing secret) ──
insert into public.bbf_app_config (key, value)
values ('sovereign_briefing_secret', gen_random_uuid()::text)
on conflict (key) do nothing;

-- ─── 3 · Token-gated read — the frontend pulls TODAY'S cached briefing blob ─────
create or replace function public.bbf_get_sovereign_briefing(p_session_token text, p_locale text default 'en')
 returns jsonb
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare
  v_user_id uuid;
  v_loc     text;
  v_row     record;
begin
  v_user_id := public._bbf_uid_from_vault_token(p_session_token);
  if v_user_id is null then
    return jsonb_build_object('ok', false, 'error', 'invalid_session');
  end if;
  -- Normalize the locale hint to en/es/pt (mirror localeCode).
  v_loc := lower(coalesce(nullif(p_locale, ''), 'en'));
  v_loc := case
    when v_loc like 'es%' then 'es'
    when v_loc like 'pt%' or v_loc like '%bras%' or v_loc like '%braz%' or v_loc = 'br' then 'pt'
    else 'en'
  end;

  select audio_b64, mime, briefing_date, chars
    into v_row
    from public.bbf_sovereign_audio
   where user_id = v_user_id and locale = v_loc and briefing_date = current_date and status = 'ready'
   order by created_at desc
   limit 1;

  if not found then
    return jsonb_build_object('ok', true, 'found', false, 'locale', v_loc);
  end if;
  return jsonb_build_object('ok', true, 'found', true, 'locale', v_loc,
    'mime', coalesce(v_row.mime, 'audio/mpeg'), 'briefing_date', v_row.briefing_date,
    'chars', v_row.chars, 'audio_b64', v_row.audio_b64);
end;
$function$;

revoke all on function public.bbf_get_sovereign_briefing(text, text) from public;
grant execute on function public.bbf_get_sovereign_briefing(text, text) to anon, authenticated, service_role;

-- ─── 4 · Tripwire: fire the briefing generator for eligible morning check-ins ──
create or replace function public._bbf_sovereign_briefing_tripwire()
returns trigger
language plpgsql
security definer
set search_path = public, extensions, net
as $$
declare
  v_fn_url    text := 'https://ihclbceghxpuawymlvgi.supabase.co/functions/v1/bbf-sovereign-briefing';
  v_secret    text;
  v_email     text;
  v_status    text;
  v_created   timestamptz;
  v_lang      text;
  v_epoch     timestamptz := '2026-06-25T00:00:00Z';
  v_graduated boolean;
begin
  -- Resolve the athlete; bail on locked accounts (cheap pre-filter, no API spend).
  select email, access_status into v_email, v_status
    from public.bbf_users where id = NEW.athlete_id and deleted_at is null limit 1;
  if v_status = 'locked' then return NEW; end if;

  -- Graduation (grandfather epoch + day>=30); undatable → graduated (fail-open).
  if v_email is not null then
    select created_at, preferred_language into v_created, v_lang
      from public.bbf_active_clients where vault_email = v_email limit 1;
  end if;
  v_graduated := (v_created is null or v_created < v_epoch or (now() - v_created) >= interval '30 days');
  if not v_graduated then return NEW; end if;  -- mid-calibration → no briefing yet

  -- Fire-and-forget. The edge fn does the precise voice_coach check, the per-day
  -- idempotency skip, and metering. Wrapped so a pg_net hiccup never blocks the check-in.
  select value into v_secret from public.bbf_app_config where key = 'sovereign_briefing_secret';
  begin
    perform net.http_post(
      url     := v_fn_url,
      headers := jsonb_build_object(
        'Content-Type', 'application/json',
        'X-BBF-Sovereign-Secret', coalesce(v_secret, '')
      ),
      body    := jsonb_build_object(
        'athlete_id', NEW.athlete_id,
        'locale',     coalesce(v_lang, 'en'),
        'source',     'tripwire'
      )
    );
  exception when others then
    raise warning '[bbf sovereign tripwire] net.http_post failed: %', sqlerrm;
  end;
  return NEW;
end;
$$;

drop trigger if exists bbf_daily_protocol_sovereign_tripwire on public.bbf_daily_protocols;
create trigger bbf_daily_protocol_sovereign_tripwire
  after insert or update on public.bbf_daily_protocols
  for each row
  execute function public._bbf_sovereign_briefing_tripwire();
