// src/lib/hyperframeWizard.js
// ─────────────────────────────────────────────────────────────────────────────
// STUDIO V4 CREATIVE WIZARD — the "Auto-Draft Hyperframe" auto-assembler.
//
// One deterministic step turns a content hook into a ready-to-voice Kinetic
// Hyperframe reel: it sets the layout on, picks the brand typography + background,
// segments the hook into kinetic cards, and derives the CTA chip. It is PURE (no
// network, no AI, no DOM) — the copy is the operator's own hook, and the voiceover
// that supplies the word-timings which animate the text is generated by the CALLER
// (StudioLayout, reusing generateStudioVoiceover) with providedScript = the hook, so
// the ElevenLabs word timings line up with the exact words on screen.
//
// CALCULATOR-OFF-LLM (CLAUDE.md §4/§8): the Wizard decides NO numbers with an LLM.
// Card breakdown, CTA derivation, and voiceover length are computed here in native
// code; the AI layer only voices the script it is handed.
// ─────────────────────────────────────────────────────────────────────────────

import { hyperframeSegments, hyperframeCta, DEFAULT_HYPERFRAME_BG } from './hyperframe.js';

// Native voiceover-length heuristic: ~2.6 spoken words/sec, clamped to the
// 15–30s text-reel band the brief calls for. Drives the VO cache key only — the
// exported reel is duration-mastered to the ACTUAL audio length (Foundry).
export function estimateVoDuration(text) {
  const words = String(text || '').trim().split(/\s+/).filter(Boolean).length;
  const secs = Math.ceil(words / 2.6);
  return Math.max(15, Math.min(30, secs || 15));
}

// Build the reelData patch that flips the Video Engine into a Kinetic Hyperframe.
// Returns { ok, reason?, patch, cards, voScript, voDuration }. `ok:false` when the
// hook is empty — the caller shows the reason instead of drafting a blank reel.
export function buildHyperframeDraft({ hook, bg } = {}) {
  const text = String(hook || '').replace(/\r/g, '').trim();
  const cards = hyperframeSegments(text, 4);
  if (!cards.length) {
    return { ok: false, reason: 'no_hook', patch: null, cards: [], voScript: '', voDuration: 0 };
  }
  return {
    ok: true,
    patch: {
      hyperframe: true,
      hyperframeBg: bg || DEFAULT_HYPERFRAME_BG,
      hook: text,                        // the hero copy — also the VO script
      hookFont: 'bebas',                 // LOCKED brand display face (§2)
      capFont: 'bebas',                  // hero cards ride the display face too
      capChunk: 4,                       // words per kinetic card
      caption_animation_style: 'word-pop',
      captionsEnabled: true,             // the words animate once the VO lands
      captionPos: 50,                    // hero text vertically centered
      overlayStyle: 'minimal',           // the brand cards carry the frame
      phoneBackdrop: false,              // full-bleed native cards, no phone mock
      watchText: hyperframeCta(text),    // CTA chip copy, derived from the payoff line
    },
    cards,
    voScript: text,
    voDuration: estimateVoDuration(text),
  };
}
